In [1]:
import sys
import string
import itertools
from collections import Counter, defaultdict
import re

from pathlib import Path
import os

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import networkx as nx
from copy import deepcopy

In [2]:
%load_ext line_profiler

In [5]:
data = Path('../data/day_13.txt').read_text()

In [22]:
d = []
fold_found = False
folds = []
max_x = 0
max_y = 0
for line in data.splitlines():
    if not line.strip():
        fold_found = True
        continue
    if not fold_found:
        x, y = [int(k) for k in line.split(',')]
        d.append((x,y))
        max_x = max(max_x, x)
        max_y = max(max_y, y)
    else:
        direction, value = line.split()[-1].split('=')
        value = int(value)
        folds.append((direction, value))

In [3]:
def part_a():
    pass

print(part_a())
# %timeit part_a()

None
45.6 ns ± 0.417 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [4]:
def part_b():
    pass

print(part_b())
# %timeit part_b()

None


In [34]:
max_x, max_y, len(d)

(1310, 892, 732)

In [47]:
447*2, 655*2

(894, 1310)

In [53]:
grid = np.zeros((max_y+3, max_x+1), dtype=bool)

for x, y in d:
    grid[y][x] = True

for i, (ins, val) in enumerate(folds):
    print(grid.shape)
    if ins == 'x':
        grid_left = grid[:,:val]
        grid_right = grid[:,val+1:]
        grid = (grid_left | np.flip(grid_right, axis=1))
    else:
        grid_top = grid[:val,:]
        grid_bot = grid[val+1:,:]
        grid = (grid_top | np.flip(grid_bot, axis=0))

    if i == 0:
        print(grid.sum())
print(grid.shape)


(895, 1311)
621
(895, 655)
(447, 655)
(447, 327)
(223, 327)
(223, 163)
(111, 163)
(111, 81)
(55, 81)
(55, 40)
(27, 40)
(13, 40)
(6, 40)


In [62]:
for row in grid:
    print(''.join(['|' if x else ' ' for x in row]))

|  | |  | |  |   ||  ||   ||    || |||| 
|  | | |  |  |    | |  | |  |    |    | 
|||| ||   |  |    | |    |  |    |   |  
|  | | |  |  |    | | || ||||    |  |   
|  | | |  |  | |  | |  | |  | |  | |    
|  | |  |  ||   ||   ||| |  |  ||  |||| 


In [28]:
grid_left = grid[:,:655]
grid_right = grid[:,656:656+655]

0

In [29]:
grid_left.shape

(1500, 655)

In [30]:
grid_right.shape

(1500, 655)

In [31]:
np.flip(grid_right, axis=1)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [37]:
(grid_left | np.flip(grid_right, axis=1)).sum()

621

In [25]:
z= np.random.randint(0, 2, (5,2))
z

array([[1, 1],
       [0, 1],
       [0, 1],
       [0, 0],
       [0, 1]])

In [27]:
np.flip(z, axis=1)

array([[1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 0]])

In [45]:
np.flip(z, axis=0)

array([[0, 1],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 1]])