In [1]:
import sys
import string
import itertools
from collections import Counter, defaultdict
import re

from pathlib import Path
import os

import pandas as pd
import numpy as np

In [2]:
data = Path('../data/day_03.txt').read_text()

In [3]:
data2 = list(zip(*data.split()))

In [4]:
bit_counters = [Counter(k) for k in data2]

In [5]:
hi, lo = '', ''
for counter in bit_counters:
    most_common = counter.most_common()
    hi += most_common[0][0]
    lo += most_common[-1][0]

print(int(hi, 2) * int(lo, 2))

2003336


In [6]:
def solve(inp, keep_hi=True):
    '''
    assume inp := list of iterable of columns
    i.e. if raw input = 
    010
    110
    then inp = [('0', '1'), ('1', '1'), ('0', '0')]
    '''
    for i in range(len(inp)):
        bit_column = inp[i]

        if len(bit_column) <= 1:
            break # as no more items to filter
        column_counter = Counter(bit_column)

        if keep_hi:
            picked_bit = '1' if column_counter['1'] >= column_counter['0'] else '0'
        else:
            picked_bit = '0' if column_counter['1'] >= column_counter['0'] else '1'

        filterd_re_ordered_inp = [k for k in zip(*inp) if k[i] == picked_bit]
        inp = list(zip(*filterd_re_ordered_inp))

    return int(''.join(list(zip(*inp))[0]), 2)

In [7]:
solve(data2), solve(data2, keep_hi=False)

(2547, 737)

In [17]:
%timeit solve(data2) * solve(data2, keep_hi=False)

671 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
arr = np.array([[int(a) for a in k] for k in data.split()])

In [14]:
np.unique(arr, return_counts=True, axis=1)

(array([[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 1, 0, ..., 0, 0, 1],
        [0, 0, 1, ..., 1, 0, 1],
        [0, 1, 0, ..., 1, 0, 1]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [16]:
np.unique(arr[:,0], return_counts=True)

(array([0, 1]), array([491, 509]))